window.CHINA_REFERRAL_JOBS = [
  {
    id: "cn-office-ops-intern",
    region: "china",
    source: "Google Doc China",
    function: "Operation",
    title: "Office Operations Intern",
    titleZh: "办公室运营实习生",
    company: "GMI Cloud",
    location: "Beijing, Wangjing",
    locationZh: "北京望京",
    postedDate: "ASAP",
    postedRelative: "一周内到岗优先",
    url: "",
    jdEn: "Office Operations Intern in Beijing. Full-time onsite internship for 3 months, 5 days per week, RMB 200/day. Responsibilities include keeping the office environment organized, managing office supplies, supporting onboarding and offboarding, procurement, vendor coordination, travel logistics, and daily office operations.",
    jdZh: "北京实习 | 硅谷 AI 公司办公室运营实习生\n\n地点：北京办公室（望京）\n到岗时间：ASAP，能一周内入职优先\n出勤要求：3 个月，每周 5 天，全职线下\n薪资：200 人民币/天\n\n我们在找一位 Office Operations Intern。如果你是细节控、喜欢把混乱变得井井有条，这个岗位很适合。\n\n你每天会做什么：\n- 环境管理：让会议室、茶水间、工区保持整洁有序。\n- 库存管理：跟进文具、零食、硬件库存，及时补货。\n- 入职支持：协助新人电脑配置、工位分配和第一天引导。\n- 离职支持：合理回收设备，配合权限管理。\n- 采购支持：采购办公用品，对接供应商，管理预算使用。\n- 后勤支持：偶尔协助老板和管理层预订机票酒店。\n\n我们希望你：\n- 人在北京，能保证每周 5 天线下到岗。\n- 细致可靠，资产登记、表格维护不能粗心。\n- 沟通能力强，需要对接保洁、保安、快递、访客和新同事。\n- 会使用 Office 365、Slack，能处理基础电脑问题更好。\n- 价值观正，以人为本，服务团队也能照顾好自己。\n\n3 个月成长路线：\n第 1 个月：盘点库存，熟悉入职/离职流程。\n第 2 个月：独立采购，并能和供应商沟通。\n第 3 个月：提出一个办公室运营优化建议。\n\n你能得到：无限量咖啡/饮料/零食、真实外企/云科技公司运营工作流、可写进简历的实习经历、扁平团队协作体验。\n\n汇报对象：Hiring Manager Alisa Yao（base 山景城）。\n投递方式：邮件标题备注「办公室运营实习+姓名+可到岗日期」。",
    criteria: { Type: "Internship", Workstyle: "Full-time onsite", Compensation: "RMB 200/day" },
    criteriaZh: { 类型: "实习", 出勤: "每周 5 天线下", 薪资: "200 元/天" }
  },
  {
    id: "cn-sa",
    region: "china",
    source: "Google Doc China",
    function: "Sales",
    title: "Solution Architect",
    titleZh: "解决方案架构师",
    company: "GMI Cloud",
    location: "Hangzhou / Shanghai / Beijing / Shenzhen",
    locationZh: "杭州 / 上海 / 北京 / 深圳",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "GPU Solution Architect role for China. Design and implement GPU cloud solutions for AI, deep learning, image processing, and HPC customers. Work closely with customer technical teams to understand business requirements, provide architecture design and technical support, and ensure delivery.",
    jdZh: "关于 GMI Cloud\n\n由 Google X 的 AI 专家与硅谷精英共同参与创立，GMI Cloud 是一家领先的 AI Native Cloud 服务商，拥有遍布全球的数据中心网络，为企业 AI 应用提供最新、最优的 GPU 资源，为全球新创公司、研究机构和大型企业提供稳定、安全、高效、经济的 AI 云服务解决方案。\n\n解决方案架构师（杭州/上海/北京/深圳）\n\n作为 GPU 解决方案架构师，你将负责设计和实施基于 GPU 的云解决方案，帮助客户解决 AI、深度学习、图像处理及其他高性能计算（HPC）领域的复杂问题。你将与客户技术团队紧密合作，深度理解业务需求，提供专业架构设计与技术支持，确保方案高效执行和落地。\n\n工作职责：\n- 技术咨询：深入了解客户在人工智能、深度学习、数据处理等领域的需求，提供 GPU 云计算技术咨询，帮助客户选择最佳云计算架构。\n- 方案设计与优化：结合公司 GPU 云资源，为客户设计最优架构方案，包括虚拟机、容器化服务、存储和网络配置优化，满足性能、可扩展性和稳定性要求。\n- 项目管理：负责从需求分析、方案设计到项目实施的全流程管理，确保项目按时交付并符合客户需求。\n- 技术演示与支持：向客户演示 GPU 云计算解决方案优势，解答架构设计和实现问题，并提供及时技术支持。\n- 产品研发支持：根据市场需求和客户反馈，协助产品研发团队优化现有 GPU 云产品并推动新功能上线。\n- 前沿技术跟踪：关注 AI、深度学习、HPC 等领域前沿技术，参与行业活动，保持技术领先。\n\n岗位要求：\n- 计算机科学、信息技术或相关专业本科及以上学历，硕士或博士优先。\n- 扎实云计算基础，熟悉 AWS、阿里云、Azure 等主流云平台，尤其具备 GPU 云计算资源使用经验。\n- 深入理解 AI 和深度学习应用场景，熟悉 TensorFlow、PyTorch 等主流 AI 框架及其在 GPU 上的优化运行。\n- 具备丰富架构设计和系统优化经验，能为高并发、高性能业务场景提供技术解决方案。",
    criteria: { Function: "Solutions / Pre-sales", Location: "China" },
    criteriaZh: { 职能: "解决方案 / 售前", 地点: "中国区" }
  },
  {
    id: "cn-tam",
    region: "china",
    source: "Google Doc China",
    function: "Sales",
    title: "Technical Account Manager",
    titleZh: "TAM 技术客户经理",
    company: "GMI Cloud",
    location: "China",
    locationZh: "中国区",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "Technical Account Manager for large-scale GPU bare-metal and container clusters. Own delivery, maintenance, troubleshooting, benchmarking, and high-priority support for VIP customers running LLM training and inference workloads.",
    jdZh: "岗位职责：\n- 负责大规模 GPU 裸金属及容器化集群的交付与日常维护。\n- 统筹裸金属生命周期管理，确保推理/训练平台所需底层软件（OS、驱动、统一存储等）高效就绪。\n- 处理复杂系统级故障，包括 Linux 内核 Panic、GPU 掉卡、XID 报错、PCIe 总线异常等。\n- 负责集群性能基准压测与验收，熟练掌握 NCCLTEST 等压测工具，监控并调优单机/多机间 Allreduce、AlltoAll 速度。\n- 作为系统侧/网络侧技术专家，与客户技术团队和运维团队紧密沟通，确保大模型训练/推理任务稳定运行。\n- 作为 VIP 客户首要技术接口人，主导 7x24 小时高优技术支持体系，确保满足高 SLA 响应要求。\n\n任职要求：\n- 5 年以上中大型数据中心 SRE、DevOps 或云计算 TAM 经验，具备强烈客户服务意识。\n- 有管理大规模 GPU 训练/推理集群的实战经验，了解 AI 算力集群从建设到维护阶段的核心痛点。\n- 熟悉 NVIDIA GPU 硬件生态（H100/A100 等）及底层拓扑结构。\n- 精通 TCP/IP、BGP、OSPF 等路由协议，理解 RDMA，精通 InfiniBand 或 RoCEv2 配置、调试及故障诊断。\n- 熟悉 Mellanox/NVIDIA 网络产品线，熟练使用 ibstat、ibnetdiscover、抓包工具等。\n- 具备优秀沟通与抗压能力，能向非网络背景客户清晰解释复杂问题并推动解决。\n- 精通 Kubernetes 生态，理解 K8s 如何感知、分配和管理底层物理 GPU 资源，熟悉容器化存储平台。\n- 熟练掌握 Linux 裸金属操作系统排障，以及 Prometheus + DCGM 等 GPU 监控体系。\n- 具备 Shell/Python 脚本开发能力，可独立开发故障判断、压测或采集脚本。\n- 性格谦和但立场坚定，能在客户与供应商之间专业沟通。\n- 拥抱变化，愿意在流程建设阶段兼任半个 SRE，具备从零到一搭建体系的自驱力。\n\n加分项：\n- 参与过 NVIDIA 千卡以上规模集群建设、交付。\n- 良好英语读写与日常沟通能力，可与 Global Infra 团队对齐技术细节。\n- 熟悉 Megatron-LM、DeepSpeed、vLLM、SGLang 或 Slurm，能听懂客户算法工程师痛点。",
    criteria: { Seniority: "Senior", Focus: "GPU cluster delivery / support" },
    criteriaZh: { 级别: "资深", 方向: "GPU 集群交付 / 客户支持" }
  },
  {
    id: "cn-fde-inference",
    region: "china",
    source: "Google Doc China",
    function: "Engineering",
    title: "Forward Deployment Engineer, Inference Engine",
    titleZh: "交付工程师（Inference Engine）",
    company: "GMI Cloud",
    location: "China",
    locationZh: "中国区",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "Forward Deployment Engineer for the Inference Engine team. Work directly with customers and partners to design, deploy, validate, and optimize LLM inference, RL, and post-training POCs on GMI GPU infrastructure.",
    jdZh: "所属团队：Inference Engine\n\n职位简介：\n我们正在寻找一位前线交付工程师（Forward Deployment Engineer, FDE），直接与客户及合作伙伴对接，在 GMI 的 GPU 基础设施上设计、部署并验证推理与强化学习（RL）的概念验证（POC）项目。\n\n这是一个高影响力、混合型工程职位，处于平台工程、应用机器学习与客户成功的交汇点。你将深入客户一线部署场景，把研究思路、数据集和业务需求转化为在真实 GPU 集群上运行的高性能系统。\n\n职责描述：\n- 全权负责客户 POC，在 GMI 集群上部署并优化 LLM 推理、RL 训练及 Post-training 工作流。\n- 将客户需求转化为具体系统设计和实验方案。\n- 与研究团队、初创公司及企业级客户保持紧密协作。\n- 在生产或预生产环境中调试系统性能、稳定性及准确性问题。\n- 搭建并调优 vLLM / SGLang / Ray Serve 等推理技术栈。\n- 优化延迟、吞吐量、GPU 利用率及成本效率。\n- 支持 RLHF / RFT / SFT 等工作流，集成 SDK、训练 API 和集群资源。\n- 诊断 GPU、网络及分布式系统瓶颈，进行多 GPU / 多节点基准测试、性能分析和压力测试。\n- 将客户需求与痛点反馈给平台、SDK 和 API 团队，协助定义参考架构、Cookbooks 和最佳实践。\n\n任职要求：\n- 深厚软件工程背景，精通 Python，熟悉 Go / Rust 优先。\n- 具备机器学习推理或训练系统实操经验。\n- 熟悉分布式系统和 GPU 技术（多卡、多机）。\n- 能直接面对客户，并处理模糊需求。\n- 具备端到端系统调试能力，覆盖代码、基础设施、网络和性能。\n\n加分项：\n- 熟悉 vLLM、SGLang、Ray Serve、Triton 等 LLM 推理框架。\n- 熟悉 RL 或 Post-training 工作流（RLHF、RFT、SFT）。\n- 熟悉 PyTorch、DeepSpeed、Megatron-LM 或类似工具。\n- 熟悉 Kubernetes 机器学习平台、GPU 性能分析与调优。\n- 曾任 FDE、Solutions Engineer、ML Platform Engineer 或 Applied Research Engineer。\n\n岗位特质：贴近真实客户和 GPU 算力，处理先进推理和强化学习负载，通过客户反馈影响产品核心走向，适合热爱最后一公里交付的构建者。",
    criteria: { Team: "Inference Engine", Type: "Customer-facing engineering" },
    criteriaZh: { 团队: "Inference Engine", 类型: "客户现场型工程" }
  },
  {
    id: "cn-go-k8s",
    region: "china",
    source: "Google Doc China",
    function: "Engineering",
    title: "Go Backend Engineer, Kubernetes Platform / AI Infra",
    titleZh: "Go 后端运维开发工程师（Kubernetes 平台 / AI Infra 方向）",
    company: "GMI Cloud",
    location: "China",
    locationZh: "中国区",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "Go backend engineering role for Kubernetes platform and AI infrastructure management. Build Container as a Service and Cluster as a Service capabilities, including cluster lifecycle, resource management, RBAC, multi-cluster, multi-tenant, and GPU resource support.",
    jdZh: "GMI Cloud｜总部山景城\nGPU 云原生 A 轮融资 8200 万美金，NVIDIA 全球 Top 6 Cloud Partner。2026 年计划投入 5 亿美金，在亚太区与 NVIDIA 合作建设万卡 GB300 AI Factory。\n\n岗位介绍：\n该岗位主要负责 Kubernetes 平台与 AI Infra 管理平台的后端研发工作，重点基于 Go 参与 Container as a Service 和 Cluster as a Service 相关平台能力建设。我们希望候选人具备扎实后端开发能力，对 Kubernetes、容器平台、集群管理、资源管理、权限控制等方向有实际使用、对接或平台开发经验。\n\n岗位职责：\n- 使用 Go 参与 Kubernetes 平台与 AI Infra 管理平台设计、开发与持续迭代。\n- 参与 Container as a Service 和 Cluster as a Service 平台建设，包括集群接入、创建、纳管、变更、回收等生命周期管理。\n- 参与容器交付、资源管理、多集群、多租户能力设计与实现。\n- 参与租户、项目、资源配额、权限控制、集群资源等基础能力平台化建设。\n- 参与 GPU 资源接入、资源管理和 AI 任务运行相关资源能力建设与优化。\n- 参与云管平台权限体系设计与开发，包括角色模型、资源授权、多团队、多命名空间、多租户场景支持。\n- 参与 Kubernetes 资源、节点、运行状态、网络、存储、权限等问题的平台侧分析与治理。\n- 通过工程化和自动化手段提升平台可维护性、稳定性和可扩展性。\n- 熟悉并使用 AI 辅助开发工具，结合 vibe coding 提升研发效率、工程质量与交付速度。\n- 编写设计文档、开发文档和技术文档，沉淀平台建设经验。\n\n任职要求：\n- 熟悉 Go 语言，具备实际后端开发经验，能独立完成模块设计与功能开发。\n- 有 Kubernetes 实际使用、对接或相关平台开发经验。\n- 了解容器平台、集群管理平台或云平台基础能力与常见场景。\n- 对集群管理、容器管理、资源管理/调度、权限管理或多租户平台有实际经验或理解。\n- 了解 Kubernetes 基本概念和常见对象，能支持相关功能开发与问题协作。\n- 使用过 Kubernetes 原生 RBAC，具备基础权限配置、排查或功能对接经验。\n- 对 Kubernetes 网络、存储、调度等概念有基本了解。\n- 熟悉现代软件开发流程，能使用 AI 辅助开发工具提升效率。\n- 具备良好工程抽象能力、问题分析能力和团队协作能力。\n\n加分项：\n- CaaS / Cluster as a Service 平台开发经验。\n- Kubernetes Controller / Operator 开发经验。\n- 多集群管理、资源纳管或云管平台开发经验。\n- AI / GPU 场景经验，如 NVIDIA Device Plugin、GPU Operator、GPU 资源接入/调度/使用支持。\n- 熟悉 Prometheus、Grafana、GPU Metrics、DCGM。\n- 大规模 GPU 集群或 AI Infra 经验，了解 Slurm 调度模型。\n- 熟悉 RBAC / ABAC / Policy-Based Access Control。",
    criteria: { Stack: "Go / Kubernetes / AI Infra", Funding: "Series A $82M" },
    criteriaZh: { 技术栈: "Go / Kubernetes / AI Infra", 融资: "A 轮 8200 万美金" }
  },
  {
    id: "cn-mle-llm-inference",
    region: "china",
    source: "Google Doc China",
    function: "Engineering",
    title: "Machine Learning Engineer, LLM Inference",
    titleZh: "机器学习工程师（LLM 推理优化）",
    company: "GMI Cloud",
    location: "China",
    locationZh: "中国区",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "Machine Learning Engineer focused on LLM inference optimization. Build a world-class inference optimization team and productionize techniques around quantization, speculative decoding, KV cache, prefill/decode disaggregation, scheduling, batching, routing, and system-level serving optimization.",
    jdZh: "关于我们：\nGMI Cloud 是一家高速成长的 AI 基础设施公司，由 Headline VC 领投。我们是全球仅有的六家获得 NVIDIA Reference Platform Cloud Partner 认证的云服务商之一，在美国和亚洲运营 8 个自建 GPU 集群，提供从 GPU 算力租赁到 AI 模型推理 API 的全方位服务。\n\n关于此角色：\n我们正在寻找一名机器学习工程师（LLM 优化方向），负责组建世界领先的推理优化团队，并将 GMI Cloud 打造为 LLM 服务性能的行业标杆。你将主导先进推理优化技术的研究、验证与生产化，并将这些技术转化为 GMI 推理平台的真实竞争优势。\n\n核心职责：\n- 主导 LLM 推理优化的前沿研究与工程实现，构建 GMI 在性能、效率和可扩展性方面的行业领先能力。\n- 针对模型执行、Runtime 和生产级推理平台，开发下一代大规模 LLM 服务优化策略。\n- 推进量化与精度优化，提升现代 GPU 系统上的吞吐量、延迟、内存效率和性价比。\n- 突破投机采样及相关加速方法，包括系统级和模型级快速生成方案。\n- 引领 KV 缓存与内存优化创新，提升长文本服务效率、内存利用率和多租户性能。\n- 为大规模生产环境开发 Prefill/Decode 分离等先进架构及分布式推理优化策略。\n- 推动调度、批处理、路由、网关编排、Adapter 服务及端到端推理效率的系统级优化。\n- 构建可扩展优化框架、性能方法论和工程实践，确保 GMI 在模型、硬件和服务模式演进中保持领先。\n- 将前沿优化构思转化为生产级能力，提升客户真实工作负载的延迟、吞吐、质量和成本表现。\n\n任职要求：\n- 在 LLM 推理系统和性能优化方面有深厚实操经验。\n- 深入理解 TTFT、ITL、吞吐量、Goodput、尾部延迟、GPU 利用率、内存效率、质量与成本的权衡。\n- 熟悉 SGLang、vLLM、TensorRT-LLM、Triton 或类似现代推理服务栈。\n- 深刻理解 GPU 推理、模型服务架构，以及计算、内存带宽、KV 缓存行为和调度相关生产瓶颈。\n- 具备强实验能力，能设计 Benchmarks、分析结果、调试性能回退，并产出有指导意义的结论。\n- 能在研究验证和生产工程之间切换，始终面向真实客户场景的可衡量影响。\n- 出色 Python 编程和系统开发能力，有 Profiling、可观测性和性能调试经验。\n- 沟通能力强，能向工程师及跨职能团队清晰解释技术权衡。\n\n加分项：\n- 1 年以上 LLM 推理优化、机器学习系统优化或相关经验。\n- 大规模模型服务优化经验，如降延迟、提吞吐、内存优化或性价比调优。\n- 熟悉量化、投机采样、KV 缓存优化、Prefill/Decode 分离或系统级服务优化。",
    criteria: { Focus: "LLM inference optimization", Stack: "SGLang / vLLM / TensorRT-LLM" },
    criteriaZh: { 方向: "LLM 推理优化", 技术栈: "SGLang / vLLM / TensorRT-LLM" }
  },
  {
    id: "cn-infra-network",
    region: "china",
    source: "Google Doc China",
    function: "Infra",
    title: "Infrastructure Engineer, Network Operations",
    titleZh: "基础设施工程师 - 网络运营",
    company: "GMI Cloud",
    location: "Beijing / Shanghai / Remote",
    locationZh: "北京 / 上海 / 远程",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "Infrastructure network operations engineer for global GPU cloud data centers. Design, build, maintain, monitor, and optimize high-performance networks for AI/ML workloads, including WAN, core, data center network, firewalls, load balancers, DNS, VPN, InfiniBand, and RoCEv2.",
    jdZh: "我们是一家来自山景城、专注为全球客户提供 NVIDIA 算力服务的 GPU Cloud 厂商，现因业务拓展需要，诚邀经验丰富的网络运营基础设施工程师加入 GMI 全球基础设施团队。\n\n理想候选人应具备 GPU 网络基础设施实践经验，并对光通信技术有深入理解。你将负责设计、构建、维护、监控和优化先进网络系统，确保高性能和高可靠性，为全球数据中心和 AI/ML 工作负载提供支持。\n\n首选工作地点：北京 / 上海 或远程\n\n你的职责：\n- 规划、设计和实施 GMI 全球数据中心网络基础设施，包括 WAN、核心网、数据中心网络、防火墙、负载均衡器、DNS、VPN 等。\n- 构建高性能网络解决方案支持 AI/ML 工作负载，覆盖计算、存储、Inband、管理和 OOB 网络，使用 InfiniBand 和以太网 RDMA RoCEv2 技术。\n- 监控和排查 GPU 网络系统故障，确保最佳性能。\n- 管理和配置光收发器及相关组件。\n- 与跨职能团队协作，理解网络相关业务需求。\n- 识别合适的网络服务提供商、供应商和解决方案。\n- 确保网络服务高性能、可扩展和 99.9% 以上可用性。\n- 实施网络安全措施并执行系统升级。\n- 记录网络配置、问题及解决方案，进行根因分析并高效解决中断。\n- 跟进光通信、GPU 网络和数据中心技术最新发展。\n- 前往 GMI 数据中心进行区域/国际出差。\n\n任职资格：\n- 计算机科学或相关领域学士学位。\n- 5 年以上高级网络工程师或相关经验。\n- 丰富的网络部署和运营支持经验。\n- 扎实网络管理和架构知识。\n- 深入了解网络安全、DDoS、IDS 等。\n- 熟悉路由器、交换机、防火墙、负载均衡器、DNS、VPN 的配置与实施。\n- 熟悉网络监控工具和协议。\n- 熟悉光网络，包括光纤、收发器和光学元件。\n- 具备高性能数据中心网络、HPC 或 AI 环境经验。\n- 优秀的问题解决、故障排查和沟通能力。\n- CCNA、CCNP 等网络认证优先。\n- 有 AI/ML GPU 网络环境实践经验者高度优先。",
    criteria: { Focus: "GPU network / Data center", Location: "Beijing / Shanghai / Remote" },
    criteriaZh: { 方向: "GPU 网络 / 数据中心", 地点: "北京 / 上海 / 远程" }
  },
  {
    id: "cn-infra-devops-backend",
    region: "china",
    source: "Google Doc China",
    function: "Infra",
    title: "Infrastructure Engineer, DevOps & Backend",
    titleZh: "基础设施工程师 - DevOps 与后端工程",
    company: "GMI Cloud",
    location: "Beijing / Shanghai / Hangzhou / Remote",
    locationZh: "北京 / 上海 / 杭州 / 可远程",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "Infrastructure backend and DevOps engineer for scalable AI/ML infrastructure. Design, build, and maintain training and inference infrastructure, automation pipelines, observability, telemetry, security, access control, and GPU cluster operations.",
    jdZh: "职位概述：\n我们正在寻找一位技术精湛的基础设施后端工程开发工程师，负责设计、构建和维护可扩展基础设施，以支持 GMI 的 AI/ML 项目。理想候选人应具备深厚云计算、分布式系统和 DevOps 实践背景，以实现高效 AI 基础设施运营。\n\n工作地：北京、上海、杭州（可远程）\n\n岗位职责：\n- 设计、实施和维护针对大规模训练和推理优化的 AI/ML 基础设施。\n- 利用 DevOps 最佳实践，开发 GPU/CPU 资源调配和工作负载调度自动化管道。\n- 开发可观测性和遥测解决方案，主动监控硬件性能、利用率和健康状况，确保集群可靠性和效率。\n- 优化基础设施，实现高吞吐数据传输和低延迟通信。\n- 管理本地部署 GPU 集群环境下的基础设施安全、访问控制和合规标准。\n- 与工程团队协作，配置和排除 GPU 集群及硬件资源故障。\n- 编写基础设施架构、部署流程、自动化工作流和运维最佳实践文档。\n- 跟进最新 GPU 技术和基础设施工程趋势，适时集成新的硬件/软件方案。\n\n职位要求：\n- 计算机科学或相关领域学士学位。\n- 精通至少一种编程语言（Golang、Python、Bash），具备扎实编码实践和系统设计能力。\n- 具有丰富基础设施编排平台经验，特别是 OpenStack 和 Kubernetes。\n- 熟练使用 Ansible、Jenkins、GitLab CI 或类似工具进行自动化、配置管理和 CI/CD 实施。\n- 拥有 Prometheus、Grafana 等遥测和可观测性方案实践经验。\n- 了解 GPU 集群中的网络、安全和性能调优。\n- 具备部署 GPU 集群和管理 GPU 工作负载的实践经验。\n- 有 HashiCorp Vault 密钥管理经验。\n- 强系统思维和抽象能力，能从端到端角度设计复杂分布式系统。\n- 深入理解 DevOps 原则、自动化和云原生架构。",
    criteria: { Stack: "OpenStack / Kubernetes / DevOps", Location: "Beijing / Shanghai / Hangzhou / Remote" },
    criteriaZh: { 技术栈: "OpenStack / Kubernetes / DevOps", 地点: "北京 / 上海 / 杭州 / 可远程" }
  },
  {
    id: "cn-video-content-intern",
    region: "china",
    source: "China role list",
    function: "Marketing",
    title: "Video Content Intern",
    titleZh: "视频内容实习生",
    company: "GMI Cloud",
    location: "Beijing, Chaoyang",
    locationZh: "北京朝阳区",
    postedDate: "Open",
    postedRelative: "开放中",
    url: "",
    jdEn: "Video Content Intern at GMI Cloud in Beijing Chaoyang. Internship commitment: 5 days per week for more than 3 months.\n\nAbout GMI Cloud:\nGMI Cloud is a fast-growing AI infrastructure startup based in Silicon Valley. We provide NVIDIA compute services to global customers and build cutting-edge technologies that power the future of AI. Through scalable GPU cloud and inference solutions, we help developers, startups, and enterprises turn AI ideas into reality.\n\nRole Overview:\nGMI Cloud is hiring a Video Content Intern to join the marketing team. You will create engaging short-form and long-form video content for WeChat Official Account, Xiaohongshu, and other channels, helping present the company's products and brand. This internship offers hands-on experience in video production, social media growth, and brand storytelling, especially in AI and cloud computing.\n\nResponsibilities:\n- Research trending topics and audience interests, then propose and plan video concepts.\n- Edit videos using Adobe Premiere Pro, After Effects, Final Cut Pro, CapCut, or similar tools.\n- Add subtitles, visual effects, and motion graphics to improve storytelling and watchability.\n- Support daily account operations, including uploads, titles, tags, descriptions, and cover design.\n- Track video performance and propose creative improvements to increase reach and engagement.\n\nRequirements:\n- Current university student; media, communications, or related majors preferred.\n- Available at least 4 days per week for more than 3 months.\n- Proficient in at least one video editing tool, such as PR, AE, Final Cut, or CapCut.\n- Familiar with Chinese video content styles and audience preferences.\n- Creative, proactive, and eager to learn video creation and marketing in the tech industry.",
    jdZh: "视频内容实习生（GMI Cloud）\n\n实习地点：北京朝阳区\n实习时间：5 天/周，持续 3 个月以上\n\n关于 GMI Cloud：\n我们是一家位于硅谷、快速成长的 AI 基础设施初创公司，致力于为全球客户提供 NVIDIA 算力服务并研发驱动人工智能未来的尖端技术。我们通过可扩展的 GPU 云和推理解决方案，为开发者、初创公司和企业赋能，帮助 AI 开发者将创意变为现实。\n\n岗位介绍：\nGMI Cloud 现招聘一名视频内容实习生加入市场团队。你将负责为微信公众号、小红书等平台制作有吸引力的短视频和长视频内容，展现公司的产品与品牌。本岗位将为你提供在视频制作、社交媒体增长和品牌故事讲述方面的实战经验，尤其是在 AI 与云计算领域。\n\n岗位职责：\n- 调研热门话题和用户兴趣，提出并策划视频选题。\n- 使用 Adobe Premiere Pro、After Effects、Final Cut Pro 或剪映等工具进行视频剪辑。\n- 添加字幕、特效和动效，提升视频的故事感与观赏性。\n- 负责日常账号运营：视频上传、标题/标签/描述优化，以及封面设计。\n- 跟踪视频表现，并提出创意优化建议，提升曝光与互动。\n\n任职要求：\n- 在校大学生，传媒、传播或相关专业优先。\n- 每周可实习至少 4 天，持续 3 个月以上。\n- 熟练掌握至少一种视频剪辑工具（PR、AE、Final Cut、剪映等）。\n- 熟悉国内视频风格和用户偏好。\n- 具备创意和主动性，乐于学习科技行业的视频创作与营销。",
    criteria: { Type: "Internship", Schedule: "5 days/week, 3+ months", Focus: "Video / Social content" },
    criteriaZh: { 类型: "实习", 时间: "5 天/周，3 个月以上", 方向: "视频 / 社媒内容" }
  },
  {
    id: "cn-technical-pm",
    region: "china",
    source: "China role list",
    function: "Engineering",
    title: "Technical Project Manager",
    titleZh: "技术项目经理",
    company: "GMI Cloud",
    location: "China",
    locationZh: "中国区",
    postedDate: "Open",
    postedRelative: "待补 JD",
    url: "",
    jdEn: "JD details are pending. This role appears in the China referral role list.",
    jdZh: "该岗位出现在中国区内推岗位名录中，当前仅有岗位名，JD 详情待补充。",
    criteria: { Status: "JD pending" },
    criteriaZh: { 状态: "JD 待补充" }
  }
];
